all: init plan

login:
		terraform login
init:
		terraform init
plan:
		terraform plan
apply:
		terraform init
		terraform plan
		terraform apply
destroy:
		terraform apply -destroy

#TODO create override for backend
